name: Smoke Test Workflow
on:
  push:
    branches:
      - main

jobs:
  k6_smoke_test:
    name: k6 smoke test run - basic example
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Run local k6 test
        uses: grafana/k6-action@v0.2.0
        with:
          filename: performance-tests/smoke-test.js

  k6_load_test:
    name: k6 load test run - basic example
    runs-on: ubuntu-latest
    needs: k6_smoke_test

    steps:
      # - name: Checkout
      #   uses: actions/checkout@v1

      - name: Run local k6 test
        uses: grafana/k6-action@v0.2.0
        with:
          filename: performance-tests/load-test.js

  k6_stress_test:
    name: k6 stress test run - basic example
    runs-on: ubuntu-latest
    needs: ['k6_smoke_test', 'k6_load_test']

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Run local k6 test
        uses: grafana/k6-action@v0.2.0
        with:
          filename: performance-tests/stress-test.js

  k6_cloud_test:
    name: k6 Cloud test run - basic example
    runs-on: ubuntu-latest
    needs: ['k6_smoke_test', 'k6_load_test', 'K6_Stress_test']

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Run cloud k6 test
        uses: grafana/k6-action@v0.2.0
        env:
          K6_CLOUD_TOKEN: ${{ secrets.K6_CLOUD_TOKEN }}
          K6_CLOUD_PROJECT_ID: ${{ secrets.K6_CLOUD_PROJECT_ID }}
        with:
          filename: performance-tests/smoke-test.js
